### PR TITLE
Add some missing files and fonts

### PR DESCRIPTION
**Pull request by nneonneo**
Some changes and improvements.

- A refined updater script which downloads all font files referenced from the DBS automatically.
- Missing files, such as language translations, the template plugin and the default sample images have been added.

### CODE REVIEW

**Comment by DUOLabs333** [comment]
Looks interesting. I'll look more into it. In the meantime though, could you reverse my latest commit on your fork. It was made accidentally.

**Comment by DUOLabs333** [comment]
How did you figure out the DBS extraction? I've been trying to figure out how he did it (and why he did it that way).

**Comment by nneonneo** [comment]
The DBS extraction is just a matter of pulling out the variables and treating them roughly as JSON. They actually aren’t exactly JSON - one variable uses the btoa() function so a proper extraction would involve evaluating the file with a JavaScript interpreter, but the present approach gets close enough. In the future this might have to be switched to using a JS interpreter if the format changes substantially. 

The font table is actually documented here: https://www.photopea.com/api/fonts. This is referenced in a comment in the DBS file.

**Comment by DUOLabs333** [comment]
Oh, I didn't even see that. That would have made extracting fonts much easier. Could you revert the deletion of the README though?

**Comment by DUOLabs333** [comment]
It looks good -- I'll merge it after I push my own commit.

**Comment by nneonneo** [comment]
FYI, although I enabled edits from maintainers, it's probably better to just request the changes you want. I've dropped the launcher commit entirely to avoid polluting history.

**Comment by nneonneo** [comment]
> Oh, I didn't even see that. That would have made extracting fonts much easier. Could you revert the deletion of the README though?

It looks like the relevant comment in DBS.js was actually added very recently, so I don't blame you for missing it :)

**Comment by DUOLabs333** [comment]
Could you remove the "www.photopea.com" directory and move the folders to the top level (and update Updater.py accordingly).

**Comment by nneonneo** [comment]
I’d suggest not to, actually: there’s a lot of directories on the website and having them all clutter the root may be confusing. Plus, I think it’s better to keep the website content separate from the bits that are specific to this project, like the updater and README. I wouldn’t be opposed to renaming the directory though, e.g. to “www” or “html”. 

It’s simple enough to launch the web server at the correct root: `python3 -m http.server --directory www.photopea.com 8887` will do it (Python 3.7+).

**Comment by DUOLabs333** [comment]
Oh, the reason why I do it like that, is because for me, it becomes standardized -- though I guess that for example, if he was to put a README.md at the base of the website, that might lead to problems.

**Comment by DUOLabs333** [comment]
Thanks for the pull request!

**Pull request merged**
